### ISSUE TITLE
update to changed grpc-go 1.53 resolver interface

### ISSUE THREAD

**Issue by mihaivint** [simplesurance/grpcconsulresolver#18] opened 2023-02-13 15:56 UTC
google.golang.org/grpc/resolver v.1.53.0  now has target.Endpoint() instead of target.Endpoint See https://pkg.go.dev/google.golang.org/grpc/resolver
# github.com/simplesurance/grpcconsulresolver/consul
../go/pkg/mod/github.com/simplesurance/grpcconsulresolver@v1.3.0/consul/builder.go:156:58: cannot use target.Endpoint (value of type func() string) as type string in argument to parseEndpoint

**Comment by fho** [comment] 2023-02-13 16:08
@mihaivint thanks, we also already stumbled upon that internally. I'll update to the newest grpc-go version soon.
I'm also happily accepting PRs for it. :-)

**Comment by mihaivint** [comment] 2023-02-14 10:17
See https://github.com/simplesurance/grpcconsulresolver/pull/20 ,  tags filtering is fixed by this as well.

**Comment by fho** [comment] 2023-02-14 10:19
>  tags filtering is fixed by this as well.

thanks for the PR! 

how? What was the cause that tags filtering did not work?

**Comment by mihaivint** [comment] 2023-02-14 10:31
I was testing only with latest  grpc and 1.52.3 and in both cases no arguments were passed for the url. I didn't track the changes but in 1.52.3 seems that target.Endpoint does not contains any arguments, nor did target.Endpoint() , while target.URL.RequestURI() does. 
I've added another commit to bump grpc version in go.mod .

**Comment by fho** [comment] 2023-02-14 17:52
fixed via https://github.com/simplesurance/grpcconsulresolver/pull/20

**Closed by fho** 2023-02-14 17:52 UTC
Labels: enhancement
